#!/bin/bash

set -x

cd "$(dirname "$0")/.."

if [ -z $ATTACH ]; then
	TOPOLOGY="$TOPOLOGY" runvm lfs -s -S  >/dev/null 2>&1 &
fi

if [ ! -z $FILE ]; then
	gdb kbuild/vmlinux --quiet \
		-ex "py TOPOLOGY=\"$TOPOLOGY\"" \
		-ex "py FILE=\"$FILE\"" \
		-x kernel/dumper.py
else
	gdb kbuild/vmlinux --quiet -ex "py TOPOLOGY=\"$TOPOLOGY\"" -x kernel/dumper.py
fi

if [ -z $ATTACH ]; then
	ps aux | grep qemu | grep -v grep | awk '{print $2}' | xargs kill -9
fi

