#!/bin/bash

cd "$(dirname "$0")/.."

set -x
if [ -z $1 ]; then
    echo "provide a disk image as \$1 please"
    exit 1
fi

if [ -z $CORES ]; then
    echo "using a default number of 2 cores"
    topology="-smp cpus=2"
elif [ "$CORES" = "16-tiered" ]; then
    topology="\
        -object memory-backend-ram,size=1G,id=m0 \
        -object memory-backend-ram,size=1G,id=m1 \
        -object memory-backend-ram,size=1G,id=m2 \
        -object memory-backend-ram,size=1G,id=m3 \
        -numa node,cpus=0-3,nodeid=0,memdev=m0 \
        -numa node,cpus=4-7,nodeid=1,memdev=m1 \
        -numa node,cpus=8-11,nodeid=2,memdev=m2 \
        -numa node,cpus=12-15,nodeid=3,memdev=m3 \
        -smp cpus=16"
else
    topology="-smp cpus=$CORES"
fi

echo "$1" | grep -e "\.qcow2$" -e '\.q$' > /dev/null
if [ "$?" = "0" ]; then
    drive="/dev/sda1"
else
    drive="/dev/sda"
fi

qemu-system-x86_64 \
    -nographic -m 4G $@ \
    -append "root=$drive rw console=tty0 console=ttyS0,115200n8 sched_verbose" \
    -kernel kbuild/arch/x86/boot/bzImage \
    -accel tcg,thread=single \
    -device virtio-net-pci,netdev=net0 -netdev user,id=net0,hostfwd=tcp::2222-:22 \
    $topology

#     -netdev user,id=net0,hostfwd=tcp::2222-:22 \
